// autogenerated by reconstant - do not edit!
public final class SAM {

	// constants
	public static final String SAM_HEADER_TAG = "HD";
	public static final String SAM_HEADER_VERSION_TAG = "VN";
	public static final String SAM_HEADER_SORTORDER_TAG = "SO";
	public static final String SAM_HEADER_GROUPORDER_TAG = "GO";
	public static final String SAM_HEADER_SUBSORT_TAG = "SS";
	public static final String SAM_HEADER_REFERENCE_SEQUENCE = "SQ";
	public static final String SAM_HEADER_SEQUENCE_LENGTH = "LN";
	public static final String SAM_HEADER_SEQUENCE_ALTERNATIVE = "AH";
	public static final String SAM_HEADER_SEQUENCE_ALTERNATIVE_NAME = "AN";
	public static final String SAM_HEADER_SEQUENCE_ASSEMBLY_ID = "AS";
	public static final String SAM_HEADER_SEQUENCE_DESCRIPTION = "DS";
	public static final String SAM_HEADER_SEQUENCE_MD5 = "M5";
	public static final String SAM_HEADER_SEQUENCE_SPECIES = "SP";
	public static final String SAM_HEADER_SEQUENCE_TOPOLOGY = "TP";
	public static final String SAM_HEADER_SEQUENCE_URI = "UR";
	public static final String SAM_HEADER_READGROUP_TAG = "RG";
	public static final String SAM_HEADER_READGROUP_ID = "ID";
	public static final String SAM_HEADER_READGROUP_BARCODE = "BC";
	public static final String SAM_HEADER_READGROUP_SEQ_CENTER = "SC";
	public static final String SAM_HEADER_READGROUP_DESCRIPTION = "DS";
	public static final String SAM_HEADER_READGROUP_DATE = "DT";
	public static final String SAM_HEADER_READGROUP_FLOWORDER = "FO";
	public static final String SAM_HEADER_READGROUP_KEY_SEQUENCE = "KS";
	public static final String SAM_HEADER_READGROUP_LIBRARY = "LB";
	public static final String SAM_HEADER_READGROUP_PROGRAMS = "PG";
	public static final String SAM_HEADER_READGROUP_PREDICTED_INSERTSIZE = "PI";
	public static final String SAM_HEADER_READGROUP_PLATFORM_TECHNOLOGY = "PL";
	public static final String SAM_HEADER_READGROUP_PLATFORM_MODEL = "PM";
	public static final String SAM_HEADER_READGROUP_PLATFORM_UNIT = "PU";
	public static final String SAM_HEADER_READGROUP_SAMPLE = "SM";
	public static final int SAM_FLAG_MULTIPLE = 1;
	public static final int SAM_FLAG_ALL_PROPERLY_ALIGNED = 2;
	public static final int SAM_FLAG_PROPERLY_PAIRED = 2;
	public static final int SAM_FLAG_SEGMENT_UNMAPPED = 4;
	public static final int SAM_FLAG_NEXT_SEGMENT_UNMAPPED = 8;
	public static final int SAM_FLAG_MATE_UNMAPPED = 8;
	public static final int SAM_FLAG_CURRENT_REVERSE_STRAND = 16;
	public static final int SAM_FLAG_NEXT_REVERSE_STRAND = 32;
	public static final int SAM_FLAG_MATE_REVERSE_STRAND = 32;
	public static final int SAM_FLAG_FIRST_SEGMENT = 64;
	public static final int SAM_FLAG_READ1 = 64;
	public static final int SAM_FLAG_LAST_SEGMENT = 128;
	public static final int SAM_FLAG_READ2 = 128;
	public static final int SAM_FLAG_SECONDARY_ALIGNMENT = 256;
	public static final int SAM_FLAG_NOT_PASSING_FILTERS = 512;
	public static final int SAM_FLAG_DUPLICATE = 1024;
	public static final int SAM_FLAG_SUPPLEMENTARY_ALIGNMENT = 2048;

	// enums
	public enum SAM_HEADER_SORT_ORDER_TYPE {
		unknown, 
		coordinate, 
		queryname, 
		strand
	}
	public enum SAM_HEADER_SUBSORT {
		lexicographical, 
		natural, 
		umi
	}
	public enum SAM_HEADER_RG_PLATFORM {
		CAPILLARY, 
		DNBSEQ, 
		ELEMENT, 
		HELICOS, 
		ILLUMINA, 
		IONTORRENT, 
		LS454, 
		ONT, 
		PACBIO, 
		SINGULAR, 
		SOLID, 
		ULTIMA
	}

}