// autogenerated by reconstant - do not edit!
public final class SamTags {

	// constants
	public static final String SAM_TAG_AM = "AM";
	public static final String SAM_TAG_AS = "AS";
	public static final String SAM_TAG_BC = "BC";
	public static final String SAM_TAG_BQ = "BQ";
	public static final String SAM_TAG_BZ = "BZ";
	public static final String SAM_TAG_CB = "CB";
	public static final String SAM_TAG_CC = "CC";
	public static final String SAM_TAG_CG = "CG";
	public static final String SAM_TAG_CM = "CM";
	public static final String SAM_TAG_CO = "CO";
	public static final String SAM_TAG_CP = "CP";
	public static final String SAM_TAG_CQ = "CQ";
	public static final String SAM_TAG_CR = "CR";
	public static final String SAM_TAG_CS = "CS";
	public static final String SAM_TAG_CT = "CT";
	public static final String SAM_TAG_CY = "CY";
	public static final String SAM_TAG_E2 = "E2";
	public static final String SAM_TAG_FI = "FI";
	public static final String SAM_TAG_FS = "FS";
	public static final String SAM_TAG_FZ = "FZ";
	public static final String SAM_TAG_GC = "GC";
	public static final String SAM_TAG_GQ = "GQ";
	public static final String SAM_TAG_GS = "GS";
	public static final String SAM_TAG_H0 = "H0";
	public static final String SAM_TAG_H1 = "H1";
	public static final String SAM_TAG_H2 = "H2";
	public static final String SAM_TAG_HI = "HI";
	public static final String SAM_TAG_IH = "IH";
	public static final String SAM_TAG_LB = "LB";
	public static final String SAM_TAG_MC = "MC";
	public static final String SAM_TAG_MD = "MD";
	public static final String SAM_TAG_MF = "MF";
	public static final String SAM_TAG_MI = "MI";
	public static final String SAM_TAG_ML = "ML";
	public static final String SAM_TAG_MM = "MM";
	public static final String SAM_TAG_MN = "MN";
	public static final String SAM_TAG_MQ = "MQ";
	public static final String SAM_TAG_NH = "NH";
	public static final String SAM_TAG_NM = "NM";
	public static final String SAM_TAG_OA = "OA";
	public static final String SAM_TAG_OC = "OC";
	public static final String SAM_TAG_OP = "OP";
	public static final String SAM_TAG_OQ = "OQ";
	public static final String SAM_TAG_OX = "OX";
	public static final String SAM_TAG_PG = "PG";
	public static final String SAM_TAG_PQ = "PQ";
	public static final String SAM_TAG_PT = "PT";
	public static final String SAM_TAG_PU = "PU";
	public static final String SAM_TAG_Q2 = "Q2";
	public static final String SAM_TAG_QT = "QT";
	public static final String SAM_TAG_QX = "QX";
	public static final String SAM_TAG_R2 = "R2";
	public static final String SAM_TAG_RG = "RG";
	public static final String SAM_TAG_RT = "RT";
	public static final String SAM_TAG_RX = "RX";
	public static final String SAM_TAG_S2 = "S2";
	public static final String SAM_TAG_SA = "SA";
	public static final String SAM_TAG_SM = "SM";
	public static final String SAM_TAG_SQ = "SQ";
	public static final String SAM_TAG_TC = "TC";
	public static final String SAM_TAG_TS = "TS";
	public static final String SAM_TAG_U2 = "U2";
	public static final String SAM_TAG_UQ = "UQ";

	// enums

}