// autogenerated by reconstant - do not edit!

// constants
pub const SAM_HEADER_TAG: &str = "HD";
pub const SAM_HEADER_VERSION_TAG: &str = "VN";
pub const SAM_HEADER_SORTORDER_TAG: &str = "SO";
pub const SAM_HEADER_GROUPORDER_TAG: &str = "GO";
pub const SAM_HEADER_SUBSORT_TAG: &str = "SS";
pub const SAM_HEADER_REFERENCE_SEQUENCE: &str = "SQ";
pub const SAM_HEADER_SEQUENCE_LENGTH: &str = "LN";
pub const SAM_HEADER_SEQUENCE_ALTERNATIVE: &str = "AH";
pub const SAM_HEADER_SEQUENCE_ALTERNATIVE_NAME: &str = "AN";
pub const SAM_HEADER_SEQUENCE_ASSEMBLY_ID: &str = "AS";
pub const SAM_HEADER_SEQUENCE_DESCRIPTION: &str = "DS";
pub const SAM_HEADER_SEQUENCE_MD5: &str = "M5";
pub const SAM_HEADER_SEQUENCE_SPECIES: &str = "SP";
pub const SAM_HEADER_SEQUENCE_TOPOLOGY: &str = "TP";
pub const SAM_HEADER_SEQUENCE_URI: &str = "UR";
pub const SAM_HEADER_READGROUP_TAG: &str = "RG";
pub const SAM_HEADER_READGROUP_ID: &str = "ID";
pub const SAM_HEADER_READGROUP_BARCODE: &str = "BC";
pub const SAM_HEADER_READGROUP_SEQ_CENTER: &str = "SC";
pub const SAM_HEADER_READGROUP_DESCRIPTION: &str = "DS";
pub const SAM_HEADER_READGROUP_DATE: &str = "DT";
pub const SAM_HEADER_READGROUP_FLOWORDER: &str = "FO";
pub const SAM_HEADER_READGROUP_KEY_SEQUENCE: &str = "KS";
pub const SAM_HEADER_READGROUP_LIBRARY: &str = "LB";
pub const SAM_HEADER_READGROUP_PROGRAMS: &str = "PG";
pub const SAM_HEADER_READGROUP_PREDICTED_INSERTSIZE: &str = "PI";
pub const SAM_HEADER_READGROUP_PLATFORM_TECHNOLOGY: &str = "PL";
pub const SAM_HEADER_READGROUP_PLATFORM_MODEL: &str = "PM";
pub const SAM_HEADER_READGROUP_PLATFORM_UNIT: &str = "PU";
pub const SAM_HEADER_READGROUP_SAMPLE: &str = "SM";
pub const SAM_FLAG_MULTIPLE: i32 = 1;
pub const SAM_FLAG_ALL_PROPERLY_ALIGNED: i32 = 2;
pub const SAM_FLAG_PROPERLY_PAIRED: i32 = 2;
pub const SAM_FLAG_SEGMENT_UNMAPPED: i32 = 4;
pub const SAM_FLAG_NEXT_SEGMENT_UNMAPPED: i32 = 8;
pub const SAM_FLAG_MATE_UNMAPPED: i32 = 8;
pub const SAM_FLAG_CURRENT_REVERSE_STRAND: i32 = 16;
pub const SAM_FLAG_NEXT_REVERSE_STRAND: i32 = 32;
pub const SAM_FLAG_MATE_REVERSE_STRAND: i32 = 32;
pub const SAM_FLAG_FIRST_SEGMENT: i32 = 64;
pub const SAM_FLAG_READ1: i32 = 64;
pub const SAM_FLAG_LAST_SEGMENT: i32 = 128;
pub const SAM_FLAG_READ2: i32 = 128;
pub const SAM_FLAG_SECONDARY_ALIGNMENT: i32 = 256;
pub const SAM_FLAG_NOT_PASSING_FILTERS: i32 = 512;
pub const SAM_FLAG_DUPLICATE: i32 = 1024;
pub const SAM_FLAG_SUPPLEMENTARY_ALIGNMENT: i32 = 2048;

// enums
pub enum SAM_HEADER_SORT_ORDER_TYPE {
	unknown, 
	coordinate, 
	queryname, 
	strand
}
pub enum SAM_HEADER_SUBSORT {
	lexicographical, 
	natural, 
	umi
}
pub enum SAM_HEADER_RG_PLATFORM {
	CAPILLARY, 
	DNBSEQ, 
	ELEMENT, 
	HELICOS, 
	ILLUMINA, 
	IONTORRENT, 
	LS454, 
	ONT, 
	PACBIO, 
	SINGULAR, 
	SOLID, 
	ULTIMA
}
