// autogenerated by reconstant - do not edit!
#ifndef AUTOGENERATED_C_SAMTAGS_H
#define AUTOGENERATED_C_SAMTAGS_H

// constants
const char* SAM_TAG_AM = "AM";
const char* SAM_TAG_AS = "AS";
const char* SAM_TAG_BC = "BC";
const char* SAM_TAG_BQ = "BQ";
const char* SAM_TAG_BZ = "BZ";
const char* SAM_TAG_CB = "CB";
const char* SAM_TAG_CC = "CC";
const char* SAM_TAG_CG = "CG";
const char* SAM_TAG_CM = "CM";
const char* SAM_TAG_CO = "CO";
const char* SAM_TAG_CP = "CP";
const char* SAM_TAG_CQ = "CQ";
const char* SAM_TAG_CR = "CR";
const char* SAM_TAG_CS = "CS";
const char* SAM_TAG_CT = "CT";
const char* SAM_TAG_CY = "CY";
const char* SAM_TAG_E2 = "E2";
const char* SAM_TAG_FI = "FI";
const char* SAM_TAG_FS = "FS";
const char* SAM_TAG_FZ = "FZ";
const char* SAM_TAG_GC = "GC";
const char* SAM_TAG_GQ = "GQ";
const char* SAM_TAG_GS = "GS";
const char* SAM_TAG_H0 = "H0";
const char* SAM_TAG_H1 = "H1";
const char* SAM_TAG_H2 = "H2";
const char* SAM_TAG_HI = "HI";
const char* SAM_TAG_IH = "IH";
const char* SAM_TAG_LB = "LB";
const char* SAM_TAG_MC = "MC";
const char* SAM_TAG_MD = "MD";
const char* SAM_TAG_MF = "MF";
const char* SAM_TAG_MI = "MI";
const char* SAM_TAG_ML = "ML";
const char* SAM_TAG_MM = "MM";
const char* SAM_TAG_MN = "MN";
const char* SAM_TAG_MQ = "MQ";
const char* SAM_TAG_NH = "NH";
const char* SAM_TAG_NM = "NM";
const char* SAM_TAG_OA = "OA";
const char* SAM_TAG_OC = "OC";
const char* SAM_TAG_OP = "OP";
const char* SAM_TAG_OQ = "OQ";
const char* SAM_TAG_OX = "OX";
const char* SAM_TAG_PG = "PG";
const char* SAM_TAG_PQ = "PQ";
const char* SAM_TAG_PT = "PT";
const char* SAM_TAG_PU = "PU";
const char* SAM_TAG_Q2 = "Q2";
const char* SAM_TAG_QT = "QT";
const char* SAM_TAG_QX = "QX";
const char* SAM_TAG_R2 = "R2";
const char* SAM_TAG_RG = "RG";
const char* SAM_TAG_RT = "RT";
const char* SAM_TAG_RX = "RX";
const char* SAM_TAG_S2 = "S2";
const char* SAM_TAG_SA = "SA";
const char* SAM_TAG_SM = "SM";
const char* SAM_TAG_SQ = "SQ";
const char* SAM_TAG_TC = "TC";
const char* SAM_TAG_TS = "TS";
const char* SAM_TAG_U2 = "U2";
const char* SAM_TAG_UQ = "UQ";

// enums

#endif /* AUTOGENERATED_C_SAMTAGS_H */